package:
  name: 'run-stardist'
  version: '0.0.4'

source:
  path: ..

build:
  noarch: python
  script: 'pip install . --no-deps --ignore-installed --no-cache-dir'
  number: 1
  entry_points:
    - train-stardist = runstardist.train:main
    - predict-stardist = runstardist.predict:main

requirements:
  build:
    - python
    - pip
  run:
    - python>=3.10 # for `|` in pydantic
    # - tensorflow
    - stardist
    - wandb
    - pydantic

about:
  home: https://github.com/kreshuklab/go-nuclear
  license: MIT
  license_family: MIT
